# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  push:
    branches:
      - develop
      - master

jobs:
  check-backend:
    name: Check Backend

    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: make build

  deploy:
    name: Deploy Backend

    needs:
      - check-backend

    if: endsWith( github.ref, 'master' )

    runs-on:
      - self-hosted

    env:
      AWS_HOSTED_ZONE_ID: ${{ secrets.AWS_HOSTED_ZONE_ID }}
      AWS_DOMAIN_NAME: ${{ secrets.AWS_DOMAIN_NAME }}
      AWS_ACM_CERTIFICATE_ARN: ${{ secrets.AWS_ACM_CERTIFICATE_ARN }}

    steps:
      - run: echo "deploying '${{ github.ref }}' to 'prd'"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn sst cdk diff --stage prd
      # TODO
      # - run: yarn sst deploy --stage prd
